### ISSUE TITLE
gtksheet crashes

### ISSUE THREAD

**Issue by songqingshan** [fpaquet/gtksheet#10]
testgtksheet.exe crashes.
I have tried gtksheet testgtksheet.exe under msys2/mingw64. There are three pages (e.g., folder 1, folder 2, and folder 3). If you start from page 1(folder 1), it works. if you visit other two pages (folder 2 or folder 3 or both) after visiting page 1, then you go back to the page 1 and the button "Show me a calendar" disappears. When clicking the some areas on the same page, the button maybe shows again (the best scenario), maybe disappears forever, maybe the program crashes (worst scenario), maybe shows warning "(testgtksheet.exe:3508): GLib-CRITICAL **: 22:43:05.957: Source ID 2344 was not found when attempting to remove it".  I check following link: https://stackoverflow.com/questions/23199699/glib-critical-source-id-xxx-was-not-found-when-attempting-to-remove-it. It says "This isn't a bug in your code, and it's not a crash either. It's actually just a warning that g_source_remove() was called to disconnect a certain event handler that was already disconnected, in this case, in code that is part of gtk." I believe this kind of saying is incorrect. testgtksheet.exe crashes. 
In addition, I make a small sheet with a button cell using gtksheet. first, the button can be seen. If we visit others, then come to the same page with the button. The button disappears forever (similar to testgtksheet.exe).

**Comment by fpaquet** [comment]
Which branch are you using?

**Comment by songqingshan** [comment]
Hello,

Thanks for your reply. Since I post it for a quite while and I have not got any response, I can not remember which branch now. Do you know how many branches? I remember I posted multiple issues in two branches.


________________________________

**Comment by fpaquet** [comment]
Sorry for the late reply, issue notifications are not yet configured properly.

The current "gtk3" branch could produce these crashes. Since last Gtk3 release, I made a lot of Bugfixes in the "gtk3_fixes" branch which should solve the crash and missing buttons. 

I'm planning to publish a bugfix release by next weekend.

The timer issue is new to me.

**Comment by songqingshan** [comment]
Hello Fredy,

Thanks for your response. I believe that the issues are caused by gtk component (e.g., gtkbuttons) mapping. Some did not map which causes ID cannot be found.  I made some changes in the gtksheet. Some of issues(like buttons disappear after turning page) are solved , but row title button or the top-left button still exists mapping issue which is not solved yet. Currently I do not have time to make commit for this issue. If you like to know what changes that I made, I can send your gtksheet in which you can find my notes.
Thank you again.
Song

________________________________

**Comment by fpaquet** [comment]
I've now released V4.3.0 for Gtk3 (branch gtk3)
https://github.com/fpaquet/gtksheet/releases/tag/V4.3.0

And published online docs V4
https://fpaquet.github.io/gtksheet/reference/index.html

This should fix the crash issue.

**Comment by songqingshan** [comment]
Hello Fredy Paquet,

Thanks for your informing me. That is great!
I will try it once I have time. I had found a few more programs which are not submitted a quite while ago . After I try your new version, I will submit them if they still exist. Thank you for your work. I believe that you solve mapping problems.

Song

________________________________

**Comment by fpaquet** [comment]
The timer issue was fixed in commit 6620015 in branch gtk3_fixes
Thank you for reporting.

**Comment by songqingshan** [comment]
Hello Fredy,
According to my experience, this issue is highly possible related to the button "0" mapping. When I delete all cells in the sheet, button "0" still is here. After a while, the button "0" is gone by clicking somewhere on the sheet.
Song

**Comment by songqingshan** [comment]
Hi Fredy,
Attached is the gtksheet that I made some changes which solves the part of mapping issues. You just need to type "shan", then you can find notes and changes that I made. I hope it is useful for you.

Song

________________________________

**Comment by songqingshan** [comment]
Hello FPaquet,
I know that you join two projects: gtkextra and gtksheet.
gtkextra includes a gtksheet. I want to know what are differences between the gtksheet in the gtkextra and the single gtksheet? Which one should we use?
I found the multiple issues in the single gtksheet version 4.2.0, 4.3.0 and 4.3.5. I want to report them. But I can not report them in git like before. I do not why?
Thanks,
Song
________________________________

**Comment by fpaquet** [comment]
Hello Song
Nobody was taking care of the plot widgets in GtkExtra. So i moved the sheet code into the GtkSheet project. 
GtkExtra is dead and unmaintained. You should be able to report bugs to the GtkSheet project.

> I can not report them in git like before. 

I'm not aware of any problems with the github bug tracking system.
Someone created a new issue no 26 on 28 Jul 2020.

Can you describe what happens when you try to create a new issue?

**Comment by songqingshan** [comment]
Hello Fredy,

I appreciate your reply.
the plot widgets in GtkExtra are very useful and important in the scientific community.  I believe that the reason  "Nobody was taking care of the plot widgets in GtkExtra" is just because nobody knows.
Can GtkExtra be used for Gtk3? If not, what do we need to do for advancing GtkExtra for Gtk3? any suggestions?
I will try to report some glitches and bugs in the gtksheet in git later. If still can not do it, I will copy them to you.
Thank you,
Song

________________________________

**Comment by fpaquet** [comment]
Hello Song

The main repo of GtkExtra is hosted on SourceForge. I was publishing request for a new maintainer in April 2018.
http://gtkextra.sourceforge.net/cms/index.php?option=com_content&view=article&id=63:new-maintainer-searched&catid=3:news

A google search reveals multiple forks and also a discussion about Gtk3 port of GtkExtra
https://stackoverflow.com/questions/22907417/can-gtkextra-work-with-gtk3

Before splitting the GtkSheet into a separate project, i was starting to add support for Gtk3. Have a look at the gtk3 branch there. I managed to get ONE of the plot widgets running with Gtk3, but capitulated on the other plot widgets due to lack of documentation and deeper understanding of the functionality.

Adrian E. Feiguin (the initiator of GtkExtra) quit the project more than 10 years ago. Since then, he didn't respond to my e-mails any further.

**Comment by songqingshan** [comment]
Hello Fredy Paquet,
I appreciate your insistency and contribution to gtkextra and gtksheet. I also believe many people do so. Although gtksheet still has some glitches and bugs, it has been used in some applications. Without your effort, there is not today's gtksheet.
Regarding gtkextra, You mentioned "Have a look at the gtk3 branch there. I managed to get ONE of the plot widgets running with Gtk3,...". But I can not find  the gtk3 branch. Can you send me a link? I would like to take a look at it.
Thanks,
Song

________________________________

**Comment by fpaquet** [comment]
When you browse sf repo, you can see branches on the left side
https://sourceforge.net/p/gtkextra/gtkextra-3/ci/master/tree/

Or simply clone the repo, then use 'git checkout gtk3'

**Comment by songqingshan** [comment]
Hello Fredy Paquet,
I appreciate your help. I down load this version and compile it successfully yesterday. Since README says it requires GTK+ 2.14.4, I assumed that I down load the wrong version. Thanks for your clarifying it.

I compile and try the gtkextra-3, gtkextra-3.3.4,gtksheet-4.2.0, gtksheet-4.3.0, and gtksheet-4.3.5. The grid in gtksheet-4.3.0 and gtksheet-4.3.5 did not show (missing). The grid in gtkextra-3, gtkextra-3.3.4,and gtksheet-4.2.0 shows well. I try to report other glitches and bugs in gtksheet-4.3.5 again, but new issue button still is dead.
Thanks for your help.
Regards,
Song


________________________________

**Comment by fpaquet** [comment]
Are you using this page for GtkSheet issues?
https://github.com/fpaquet/gtksheet/issues

I can see a green button "New Issue", which is active.
The same button also on top of this page here, it's active.
